name: Upgrade dependency locks

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  upgrade-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8eb1f6a495037164bea451156472f35fdd6bafc0
        with:
          submodules: "true"

      - name: Set up Python 3.11
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.11"

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./dev-requirements.txt

      - name: Upgrade dependency locks
        run: python -m nox -s freeze-locks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e
        with:
          author: "always-on-duty[bot] <120557446+always-on-duty[bot]@users.noreply.github.com>"
          branch: task/upgrade-deps
          commit-message: Upgrade dependency locks
          committer: "always-on-duty[bot] <120557446+always-on-duty[bot]@users.noreply.github.com>"
          title: Upgrade dependency locks
          token: ${{ secrets.ACTIONS_TOKEN || secrets.GITHUB_TOKEN }}
